dj_fantasy_baseball/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('djfb.urls')),
    path('admin/', admin.site.urls),
]

djfb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('mlb/season/<season_yr>/', views.mlb_season_overview, name='mso'),
    path('mlb/team/<team_id>/', views.mlb_team_profile, name='mtp'),
    path('player/<player_id>/', views.player_profile, name='pp'),
]

djfb/models.py
import datetime
from django.db import models


# MLB models
class MLB_Season(models.Model):
    year = models.IntegerField()

    def __str__(self):
        return(str(self.year))


class MLB_League(models.Model):
    name = models.CharField(max_length=50)
    mlb_season = models.ForeignKey('MLB_Season',
                                   on_delete=models.CASCADE)

    def __str__(self):
        return('{} - {}'.format(self.name,
                                self.mlb_season.year)
               )


class MLB_Division(models.Model):
    name = models.CharField(max_length=50)
    mlb_league = models.ForeignKey('MLB_League',
                                   on_delete=models.CASCADE)

    def __str__(self):
        return('{} {} - {}'.format(self.mlb_league
                                   .mlb_season.year,
                                   self.mlb_league.name,
                                   self.name)
               )


class MLB_Team(models.Model):
    full_name = models.CharField(max_length=100)
    common_name = models.CharField(max_length=50)
    url = models.CharField(max_length=50)
    team_id = models.IntegerField()
    primary_color = models.CharField(max_length=8)
    secondary_color = models.CharField(max_length=8)
    tertiary_color = models.CharField(max_length=8)

    mlb_division = models.ForeignKey('MLB_Division',
                                     on_delete=models.CASCADE)

    def __str__(self):
        return('{} - {}'.format(self.full_name,
                                self.mlb_division
                                .mlb_league
                                .mlb_season.year)
               )

# Player models


class Player(models.Model):
    gd_id = models.IntegerField()
    name_full = models.CharField(max_length=50)
    name_use = models.CharField(max_length=50)
    name_last = models.CharField(max_length=50)
    position = models.CharField(max_length=2, null=True, blank=True)
    height_ft = models.IntegerField(null=True, blank=True)
    height_in = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    throws = models.CharField(max_length=2, null=True, blank=True)
    bats = models.CharField(max_length=2, null=True, blank=True)
    debut = models.DateField(null=True, blank=True)
    birth = models.DateField(null=True, blank=True)

    def __str__(self):
        return(self.name_full)


class Roster(models.Model):
    player = models.ForeignKey('Player',
                               on_delete=models.CASCADE)
    team = models.ForeignKey('MLB_Team',
                             on_delete=models.CASCADE)
    start = models.DateField()
    end = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['player__name_last']

    def __str__(self):
        return('{} - {}'.format(
            self.player.name_full,
            self.team.full_name)
        )


# MLB games and stats
class MLB_Game(models.Model):
    gd_id = models.CharField(max_length=50)
    date = models.DateTimeField()
    away_team = models.ForeignKey('MLB_Team',
                                  related_name='away_team_game_set',
                                  on_delete=models.CASCADE)
    home_team = models.ForeignKey('MLB_Team',
                                  related_name='home_team_game_set',
                                  on_delete=models.CASCADE)
    away_team_runs = models.IntegerField()
    home_team_runs = models.IntegerField()
    winning_team = models.ForeignKey('MLB_Team',
                                     related_name='winning_team_game_set',
                                     on_delete=models.CASCADE)
    losing_team = models.ForeignKey('MLB_Team',
                                    related_name='losing_team_game_set',
                                    on_delete=models.CASCADE)

    def __str__(self):
        return('{}: {} at {}'.format(
            datetime.date.strftime(self.date, '%Y-%m-%d'),
            self.away_team.common_name,
            self.home_team.common_name
        ))


class Batter_Game(models.Model):
    mlb_game = models.ForeignKey('MLB_Game',
                                 on_delete=models.CASCADE)
    player = models.ForeignKey('Player',
                               on_delete=models.CASCADE)
    pa = models.IntegerField()
    ab = models.IntegerField()
    h = models.IntegerField()
    bb = models.IntegerField()
    hbp = models.IntegerField()
    single = models.IntegerField()
    double = models.IntegerField()
    triple = models.IntegerField()
    hr = models.IntegerField()
    r = models.IntegerField()
    rbi = models.IntegerField()
    sb = models.IntegerField()
    so = models.IntegerField()
    pitcher = models.BooleanField()
    catcher = models.BooleanField()
    first = models.BooleanField()
    second = models.BooleanField()
    third = models.BooleanField()
    short = models.BooleanField()
    left = models.BooleanField()
    center = models.BooleanField()
    right = models.BooleanField()
    dh = models.BooleanField()

    def __str__(self):
        return('{}: {} at {} -- {}'.format(
            datetime.date.strftime(self.mlb_game.date, '%Y-%m-%d'),
            self.mlb_game.away_team.common_name,
            self.mlb_game.home_team.common_name,
            self.player.name_full
        ))


class Pitcher_Game(models.Model):
    mlb_game = models.ForeignKey('MLB_Game',
                                 on_delete=models.CASCADE)
    player = models.ForeignKey('Player',
                               on_delete=models.CASCADE)
    w = models.BooleanField()
    l = models.BooleanField()
    sv = models.BooleanField()
    outs = models.IntegerField()
    so = models.IntegerField()
    bb = models.IntegerField()
    h = models.IntegerField()
    hr = models.IntegerField()
    er = models.IntegerField()
    r = models.IntegerField()
    bf = models.IntegerField()
    game_score = models.IntegerField()

    def __str__(self):
        return('{}: {} at {} -- {}'.format(
            datetime.date.strftime(self.mlb_game.date, '%Y-%m-%d'),
            self.mlb_game.away_team.common_name,
            self.mlb_game.home_team.common_name,
            self.player.name_full
        ))


# Fantasy League Models

class Fantasy_League(models.Model):
    mlb_season = models.ForeignKey('MLB_Season', on_delete=models.CASCADE)
    num_teams = models.IntegerField()
    keeper = models.BooleanField()
    trade_deadline = models.DateField()
    scoring = models.CharField(max_length=4,
                               choices= (
                                   ('ROTO', 'Roto'),
                                   ('PNT', 'Points'),
                               ))
                                   
class Roto_Cat(models.Model):
    fantasy_league = models.ForeignKey('fantasy_league', on_delete=models.CASCADE)
    category = models.CharField(max_length=50)

class Point_Val(models.Model):
    fantasy_league = models.ForeignKey('fantasy_league', on_delete=models.CASCADE)
    stat = models.CharField(max_length=10)
    value = models.DecimalField(max_digits=5, decimal_places=2)
    
class Fantasy_Team(models.Model):
    fantasy_league = models.ForeignKey('fantasy_league', on_delete=models.CASCADE)

djfb/views.py
from django.db.models import Sum, Avg, Q, F, Case, Count, When
from django.db.models.functions import TruncYear
from django.http import HttpResponse
from django.shortcuts import render
from djfb.models import *
import pdb


def index(request):
    context = {
    }
    return render(
        request,
        'djfb/index.html',
        context
    )


def mlb_season_overview(request, season_yr):
    season = MLB_Season.objects.get(year=season_yr)

    context = {
        'season': season
    }

    return render(
        request,
        'djfb/mlb_season_overview.html',
        context
    )


def mlb_team_profile(request, team_id):
    team = MLB_Team.objects.get(id=team_id)

    context = {
        'team': team,
    }

    return render(
        request,
        'djfb/mlb_team_profile.html',
        context
    )


def player_profile(request, player_id):
    player = Player.objects.get(id=player_id)

    # eligibility

    elig = (Batter_Game
            .objects
            .filter(player=player)
            .annotate(year=TruncYear('mlb_game__date__year'))
            .values('year')
            .annotate(
                p=Count(Case(When(pitcher=True, then=1))),
                ut=Count(Case(When(pitcher=False, then=1))),
                c=Count(Case(When(catcher=True, then=1))),
                fb=Count(Case(When(first=True, then=1))),
                sb=Count(Case(When(second=True, then=1))),
                tb=Count(Case(When(third=True, then=1))),
                ss=Count(Case(When(short=True, then=1))),
                lf=Count(Case(When(left=True, then=1))),
                cf=Count(Case(When(center=True, then=1))),
                rf=Count(Case(When(right=True, then=1))),
                dh=Count(Case(When(dh=True, then=1)))
            )
            .order_by('year')
            )

    # get hitting stats
    bstats = (Batter_Game
              .objects
              .filter(player=player)
              .annotate(year=TruncYear('mlb_game__date__year'))
              .values('year')
              .annotate(pa=Sum('pa'),
                        ab=Sum('ab'),
                        h=Sum('h'),
                        r=Sum('r'),
                        hr=Sum('hr'),
                        rbi=Sum('rbi'),
                        sb=Sum('sb'),
                        bb=Sum('bb'),
                        singles=Sum('single'),
                        doubles=Sum('double'),
                        triples=Sum('triple'),
                        )
              .order_by('year')
              )

    for bstats_yr in bstats:
        # batting average
        try:
            bstats_yr['avg'] = round(1.0 * bstats_yr['h'] / bstats_yr['ab'], 3)
        except (ZeroDivisionError, TypeError):
            bstats_yr['avg'] = 0.000

            # on base percentage
            try:
                bstats_yr['obp'] = round((1.0 * bstats_yr['h'] +
                                          bstats_yr['bb']) / bstats_yr['pa'], 3)
            except (ZeroDivisionError, TypeError):
                bstats_yr['obp'] = 0.000

            # slugging percentage
            try:
                bstats_yr['slg'] = round((1.0 * bstats_yr['singles']
                                          + 2.0 * bstats_yr['doubles']
                                          + 3.0 * bstats_yr['triples']
                                          + 4.0 * bstats_yr['hr']) / bstats_yr['ab'], 3)
            except (ZeroDivisionError, TypeError):
                bstats_yr['slg'] = 0.000

    # get pitching stats
    pstats = (Pitcher_Game
              .objects
              .filter(player=player)
              .annotate(year=TruncYear('mlb_game__date__year'))
              .values('year')
              .annotate(
                  w=Count(Case(When(w=True, then=1))),
                  l=Count(Case(When(l=True, then=1))),
                  sv=Count(Case(When(sv=True, then=1))),
                  so=Sum('so'),
                  h=Sum('h'),
                  bb=Sum('bb'),
                  er=Sum('er'),
                  outs=Sum('outs'))
              )

    for pstats_yr in pstats:
        # ERA
        try:
            pstats_yr['era'] = round(
                9.0 * pstats_yr['er'] / pstats_yr['outs']/3, 3)
        except (ZeroDivisionError, TypeError):
            pstats_yr['era'] = 0.000

        # WHIP
        try:
            pstats_yr['whip'] = round(
                1.0 * (pstats_yr['bb'] + pstats_yr['h']) / pstats_yr['outs']/3, 3)
        except (ZeroDivisionError, TypeError):
            pstats_yr['whip'] = 0.000

    context = {
        'player': player,
        'elig': elig,
        'bstats': bstats,
        'pstats': pstats,
    }

    return render(
        request,
        'djfb/player_profile.html',
        context
    )

djfb/templates/djfb/base.html
<!DOCTYPE html>
<html>
    <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>

	<link rel = "stylesheet" href = "https://fonts.googleapis.com/icon?family=Material+Icons">
	<!-- Compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	{% load static %}
	<link rel="stylesheet" href="{% static 'djfb/css/custom.css' %}"
	
	{% block head %}{% endblock %}
	
    </head>
    
    <body>
	
	{% include 'djfb/header.html' %}

	<main class="container">
	    {% block content %}
	    {% endblock %}
	</main>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	{% load static %}
	<script src="{% static 'djfb/js/custom.js' %}"></script>
    </body>
</html>

djfb/templates/djfb/header.html
<header>
    <div class="container"><a href="#" data-target="nav-mobile" class="top-nav sidenav-trigger waves-effect waves-light circle hide-on-large-only"><i class="material-icons">menu</i></a></div>
    <ul id="nav-mobile" class="sidenav sidenav-fixed">
        <li class="logo"><a id="logo-container" href="/" class="brand-logo">
	    {% load static %}
            <object id="front-page-logo" type="image/svg+xml" data="{% static 'djfb/logo.svg' %}" style="height:100%; display:inline-block;">Your browser does not support SVG</object></a></li>

        <li class="bold active"><a href="about.html" class="waves-effect waves-teal">About</a></li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
		<li class="bold"><a class="collapsible-header waves-effect waves-teal">MLB</a>
		    <div class="collapsible-body">
			<ul>
			    <li><a href="/mlb/season/2018">2018 Season</a></li>
			</ul>
		    </div>
		</li>
            </ul>
        </li>
    </ul>
</header>

djfb/templates/djfb/index.html
{% extends 'djfb/base.html' %}

{% block title %}DJFB{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    
    <h1> Hello World</h1>
    
{% endblock %}

djfb/templates/djfb/mlb_season_overview.html
{% extends 'djfb/base.html' %}

{% block title %}DJFB{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    <main>
	<h1>MLB Structure for {{ season.year }}</h1>
	{% for league in season.mlb_league_set.all %}
	    <h3>{{ league.name }}</h3>
	    {% for division in league.mlb_division_set.all %}
		<li>{{ division.name }}
		    <ul>
			{% for team in division.mlb_team_set.all %}
			    <li><a href="/mlb/team/{{ team.id }}">{{ team.full_name }}</a></li>
			{% endfor %}
		    </ul>
		</li>
	    {% endfor %}
	{% endfor %}
    </main>
{% endblock %}
    

djfb/templates/djfb/mlb_team_profile.html
{% extends 'djfb/base.html' %}

{% block title %}DJFB{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    <main>
	<h1>{{ team.full_name }}</h1>

	<h3>Current Roster</h3>

	{% for rost in team.roster_set.all %}
	    {% if not rost.player.end %}
		<li><a href="/player/{{ rost.player.id }}"> {{ rost.player }}</a></li>
	    {% endif %}
	{% endfor %}
	
    </main>
{% endblock %}
    

djfb/templates/djfb/player_profile.html
{% extends 'djfb/base.html' %}

{% block title %}DJFB{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
    <main>
	<h1>{{ player.name_full }}</h1>

	{% if not elig %}
	    <h4>No games so no stats</h4>
	{% endif %}

	{% for bstats_yr in bstats %}
	    {% if bstats_yr.pa > 0 %}
		<h4>Batting Stats</h4>
		<table>
		    <thead>
			<th>Season</th>
			<th>Avg</th>
			<th>R</th>
			<th>HR</th>
			<th>RBI</th>
			<th>SB</th>
		    </thead>
		    <tbody>
			<td>{{ bstats_yr.year.year }}</td>
			<td>{{ bstats_yr.avg }}</td>
			<td>{{ bstats_yr.r }}</td>
			<td>{{ bstats_yr.hr }}</td>
			<td>{{ bstats_yr.rbi }}</td>
			<td>{{ bstats_yr.sb }}</td>
		    </tbody>
		</table>
	    {% endif %}
	{% endfor %}

	{% for pstats_yr in pstats %}
	    {% if pstats_yr.outs > 0 or pstats_yr.bb > 0 or pstats_yr.h > 0 %}
		<h4>Pitching Stats</h4>
		
		<table>
		    <thead>
			<th>Season</th>
			<th>W</th>
			<th>SV</th>
			<th>K</th>
			<th>ERA</th>
			<th>WHIP</th>
		    </thead>
		    <tbody>
			<td>{{ pstats_yr.year.year }}</td>
			<td>{{ pstats_yr.w }}</td>
			<td>{{ pstats_yr.sv }}</td>
			<td>{{ pstats_yr.so }}</td>
			<td>{{ pstats_yr.era }}</td>
			<td>{{ pstats_yr.whip }}</td>
		    </tbody>
		</table>
		
	    {% endif %}
	{% endfor %}

	<h4>Batting Gamelog</h4>
	
    </main>
{% endblock %}